# Generated by Django 6.0.5 on 2026-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Enter Text Here')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
